// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransactionManagement.Data;

#nullable disable

namespace TransactionManagement.Migrations
{
    [DbContext(typeof(TransactionDbContext))]
    partial class TransactionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TransactionManagement.Entity.Transaction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<double>("buyAmount")
                        .HasColumnType("double")
                        .HasColumnName("buyAmount");

                    b.Property<double>("buyPrice")
                        .HasColumnType("double")
                        .HasColumnName("buyPrice");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdAt");

                    b.Property<string>("cryptoName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("cryptoName");

                    b.Property<string>("cryptoSymbol")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("cryptoSymbol");

                    b.Property<int>("portfolioId")
                        .HasColumnType("int")
                        .HasColumnName("portfolioId");

                    b.Property<double>("sellAmount")
                        .HasColumnType("double")
                        .HasColumnName("sellAmount");

                    b.Property<double>("sellPrice")
                        .HasColumnType("double")
                        .HasColumnName("sellPrice");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.HasKey("id");

                    b.ToTable("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
