version: '3.4'

networks:
  backend:
  frontend:

services:
  usermanagement:
    container_name: usermanagement
    image: artemivl/usermanagement:latest
    networks:
      - backend
      - frontend
    ports:
      - 8003:443

  portfoliomanagement:
    container_name: portfoliomanagement
    image: artemivl/portfoliomanagement:latest
    networks:
      - backend
      - frontend
    ports:
      - 8004:443

  cryptocurrencydata:
    container_name: cryptocurrencydata
    image: artemivl/cryptocurrencydata:latest
    networks:
      - backend
      - frontend
    ports:
      - 8005:443

  transactionmanagement:
    container_name: transactionmanagement
    image: artemivl/transactionmanagement:latest
    networks:
      - backend
      - frontend
    ports:
      - 8006:443
  
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: "rabbitmq:3.12.10-management"
    networks:
      - backend
    ports:
      - "5672:5672"  # AMQP port
      - "15672:15672"  # RabbitMQ management interface

  cryptradefront:
    container_name: cryptradefront
    image: artemivl/cryptradefront:latest
    networks:
      - frontend
    ports:
      - 8002:3000
