// <auto-generated />
using System;
using CryptocurrencyData.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CryptocurrencyData.Migrations
{
    [DbContext(typeof(CryptoDbContext))]
    partial class CryptoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CryptocurrencyData.Models.CryptoData", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("lastUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<double>("marketCap")
                        .HasColumnType("double");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("percentChange24h")
                        .HasColumnType("double");

                    b.Property<double>("price")
                        .HasColumnType("double");

                    b.Property<string>("symbol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("volume24h")
                        .HasColumnType("double");

                    b.HasKey("id");

                    b.ToTable("CryptoData");
                });
#pragma warning restore 612, 618
        }
    }
}
