// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransactionManagement.Data;

#nullable disable

namespace TransactionManagement.Migrations
{
    [DbContext(typeof(TransactionDbContext))]
    [Migration("20240117131745_YourMigrationName")]
    partial class YourMigrationName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TransactionManagement.Entity.Transaction", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<double>("amount")
                        .HasColumnType("double")
                        .HasColumnName("amount");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("createdAt");

                    b.Property<string>("cryptoName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("cryptoName");

                    b.Property<string>("cryptoSymbol")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("cryptoSymbol");

                    b.Property<int>("portfolioId")
                        .HasColumnType("int")
                        .HasColumnName("portfolioId");

                    b.Property<double>("price")
                        .HasColumnType("double")
                        .HasColumnName("price");

                    b.HasKey("id");

                    b.ToTable("Transactions");
                });
#pragma warning restore 612, 618
        }
    }
}
