apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: cryptocurrencydata
  name: cryptocurrencydata
spec:
  ports:
    - name: "8005"
      port: 8005
      targetPort: 443
  selector:
    io.kompose.service: cryptocurrencydata
