apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.32.0 (HEAD)
  labels:
    io.kompose.service: usermanagement
  name: usermanagement
spec:
  ports:
    - name: "8003"
      port: 8003
      targetPort: 443
  selector:
    io.kompose.service: usermanagement
