// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TradingManagement.Data;

#nullable disable

namespace TradingManagement.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    [Migration("20240118151541_YourMigrationName")]
    partial class YourMigrationName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TradingManagement.Entity.Order", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<double>("amount")
                        .HasColumnType("double")
                        .HasColumnName("amount");

                    b.Property<double>("closePrice")
                        .HasColumnType("double")
                        .HasColumnName("closePrice");

                    b.Property<string>("cryptoName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("cryptoName");

                    b.Property<string>("cryptoSymbol")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("cryptoSymbol");

                    b.Property<bool>("finished")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Finished");

                    b.Property<bool>("isOpen")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("isOpen");

                    b.Property<double>("openPrice")
                        .HasColumnType("double")
                        .HasColumnName("openPrice");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("type");

                    b.Property<int>("userId")
                        .HasColumnType("int")
                        .HasColumnName("userId");

                    b.HasKey("id");

                    b.ToTable("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
